site_name: Oasis
#site_url: 
site_description: The documentation of Oasis Optimization Algorithm
site_author: Mostafa Farrag

repo_url: https://github.com/MAfarrag/Oasis
edit_url: ""

theme:
    name: readthedocs

nav:
    - Home: index.md
    - Installation: Installation.md
    - Getting Started: Getting Started.md
    - License: LICENSE0.md